# Generated by Django 3.1.7 on 2021-03-04 13:24

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import service_stellar_signer.enums


class Migration(migrations.Migration):

    dependencies = [
        ('service_stellar_signer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keypair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('private_key', models.CharField(max_length=250)),
                ('public_key', models.CharField(db_index=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('transaction_object', models.TextField()),
                ('signed_transaction_object', models.TextField()),
                ('rehive_transaction_id', models.UUIDField(db_index=True)),
                ('status', enumfields.fields.EnumField(db_index=True, default='unsigned', enum=service_stellar_signer.enums.TransactionStatus, max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='secret',
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='backup_public_key',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='hot_wallet_public_key',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='keypair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_stellar_signer.keypair'),
        ),
    ]
