# Generated by Django 3.1.7 on 2021-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_stellar_signer', '0002_auto_20210304_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='blocked',
            new_name='block_transactions',
        ),
    ]
