# Generated by Django 3.1.7 on 2021-03-10 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_stellar_signer', '0003_auto_20210304_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_stellar_signer.user'),
        ),
    ]
