# Generated by Django 3.1.7 on 2021-03-25 21:50

from django.db import migrations, models
import enumfields.fields
import service_stellar_signer.enums


class Migration(migrations.Migration):

    dependencies = [
        ('service_stellar_signer', '0004_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypair',
            name='private_key',
        ),
        migrations.AddField(
            model_name='keypair',
            name='encrypted_private_key',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='keypair',
            name='kms_key',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='keypair',
            name='kms_keyring',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='keypair',
            name='kms_project',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='keypair',
            name='kms_region',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='keypair',
            name='type',
            field=enumfields.fields.EnumField(db_index=True, default='encrypted key', enum=service_stellar_signer.enums.KeypairType, max_length=24),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='public_key',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
