# Generated by Django 3.1.7 on 2021-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_stellar_signer', '0006_auto_20211006_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='setup',
            field=models.BooleanField(default=False),
        ),
    ]
